site_name: Documentation
theme:
  name: material
  logo: assets/echomav-small-black-bg.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:    
      primary: black
      accent: blue
extra:
  homepage: https://echomav.com
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/echomav
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Greek
      link: /el/
      lang: el
    - name: Ukrainian
      link: /uk/
      lang: uk


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="echomav.com"  target="_blank" rel="noopener">EchoMAV, LLC</a>
